### ISSUE TITLE
GitHub URL missing from NPM page

### ISSUE THREAD

**Issue by phocks** [AshKyd/jankdefer#2]
Unless I'm missing something it looks like the github url isn't mentioned on the npm page https://www.npmjs.com/package/jankdefer

So I had to google jankdefer github to find it. I don't think I can add it myself though. Cheers and I hope this saves someone else a few clicks.

**Comment by phocks** [comment]
Should be fixed by #3

**Comment by AshKyd** [comment]
Thanks @phocks, your PR fixed it. You rock.
